language: android

jdk:
    - oraclejdk7

android:
  components:
    - build-tools-21.1.1
    - android-16
    - android-19
    - android-21
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-google-google_play_services

script:
    - TERM=dumb ./gradlew test
